
from virtual_literature_companion.llm.clean_text import clean_text


EXAMPLES = [
    {
        "inp": "Brave New World 13\nChapter 1\nA squat grey building of only thirty-four stories. Over the main\nentrance the words, CENTRALLONDONHATCHERYANDCONDITIONING\nCENTRE, and, in a shield, the World State’s motto, COMMUNITY,\nIDENTITY, STABILITY.\nThe enormous room on the ground floor faced towards the north. Cold\nfor all the summer beyond the panes, for all the tropical heat of the\nroom itself, a harsh thin light glared through the windows, hungrily\nseeking some draped lay figure, some pallid shape of academic\ngoose-flesh, but finding only the glass and nickel and bleakly shining\nporcelain of a laboratory. Wintriness responded to wintriness. The\noveralls of the workers were white, their hands gloved with a pale\ncorpse-coloured rubber. The light was frozen, dead, a ghost. Only\nfrom the yellow barrels of the microscopes did it borrow a certain rich\nand living substance, lying along the polished tubes like butter, streak\nafter luscious streak in long recession down the work tables.\n“And this,” said the Director opening the door, “is the Fertilizing Room.”\nBent over their instruments, three hundred Fertilizers were plunged,\nas the Director of Hatcheries and Conditioning entered the room, in\nthe scarcely breathing silence, the absent-minded, soliloquizing hum\nor whistle, of absorbed concentration. A troop of newly arrived stu-\ndents, very young, pink and callow, followed nervously, rather abjectly,\nat the Director’s heels. Each of them carried a notebook, in which,\nwhenever the great man spoke, he desperately scribbled. Straight\nfrom the horse’s mouth. It was a rare privilege. The D.H.C. for Central\nLondon always made a point of personally conducting his new stu-\ndents round the various departments.\n“Just to give you a general idea,” he would explain to them. For of\ncourse some sort of general idea they must have, if they were to do",
        "expected_out": "A squat grey building of only thirty-four stories. Over the main\nentrance the words, CENTRAL LONDON HATCHERY AND CONDITIONING\nCENTRE, and, in a shield, the World State’s motto, COMMUNITY,\nIDENTITY, STABILITY.\nThe enormous room on the ground floor faced towards the north. Cold\nfor all the summer beyond the panes, for all the tropical heat of the\nroom itself, a harsh thin light glared through the windows, hungrily\nseeking some draped lay figure, some pallid shape of academic\ngoose-flesh, but finding only the glass and nickel and bleakly shining\nporcelain of a laboratory. Wintriness responded to wintriness. The\noveralls of the workers were white, their hands gloved with a pale\ncorpse-coloured rubber. The light was frozen, dead, a ghost. Only\nfrom the yellow barrels of the microscopes did it borrow a certain rich\nand living substance, lying along the polished tubes like butter, streak\nafter luscious streak in long recession down the work tables.\n“And this,” said the Director opening the door, “is the Fertilizing Room.”\nBent over their instruments, three hundred Fertilizers were plunged,\nas the Director of Hatcheries and Conditioning entered the room, in\nthe scarcely breathing silence, the absent-minded, soliloquizing hum\nor whistle, of absorbed concentration. A troop of newly arrived stu-\ndents, very young, pink and callow, followed nervously, rather abjectly,\nat the Director’s heels. Each of them carried a notebook, in which,\nwhenever the great man spoke, he desperately scribbled. Straight\nfrom the horse’s mouth. It was a rare privilege. The D.H.C. for Central\nLondon always made a point of personally conducting his new stu-\ndents round the various departments.\n“Just to give you a general idea,” he would explain to them. For of\ncourse some sort of general idea they must have, if they were to do",
    },
    {
        "inp": "CRIME AND\nPUNISHMb yENT\nF D\nY O\nO D O S T\nR O\nY\nE\nV\nS\nK\nY\ntranslated 6ycoNSTANCK garnbt t\nTHE\nMODERN LIBRARY\nNEW YORK",
        "expected_out": "CRIME AND PUNISHMENT\nby FYODOR DOSTOYEVSKY\ntranslated by CONSTANCE GARNETT\nTHE MODERN LIBRARY\nNEW YORK",
    },
    {
        "inp": "CRIME AND PUNISHMENT 9\n**His wife a year he fondly loved\nHis wife a — a year he — fondly loved.**\nOr suddenly waking up again:\n\"Walking along the crowded row\nHe met the one he used to know.\"\nBut no one shared his enjoyment: his silent companion looked\nwith positive hostility and mistrust at all these manifestations.\nThere was another man in the room who looked somewhat like\na retired government clerk. He was sitting apart, now and then\nsipping from his pot and looking round at the company. He,\ntoo, appeared to be in some agitation.\nCHAPTER n\nRaskolnikov was not used to crowds, and, as we said before,\nhe avoided society of every sort, more especially of late. But now\nall at once he felt a desire to be with other people. Something\nnew seemed to be taking place within him, and with it he felt\na sort of thirst for company. He was so weary after a whole\nmonth of concentrated wretchedness and gloomy excitement\nthat he longed to rest, if only for a moment, in some other world,\nwhatever it might be; and, in spite of the filthiness of the sur-\nroundings, hew as glad now to stay in the tavern.\nThe master of the establishment was in another room, but he\nfrequently came down some steps into the main room, his\njaunty, tarred boots with red turn-over tops coming into view\neach time before the rest of his person. He wore a full coat and\na horribly greasy black satin waistcoat, with no cravat, and his\nwhole face seemed smeared with oil like an iron lock. At the\ncounter stood a boy of about fourteen, and there was another\nboy somewhat younger who handed whatever was wanted. On\nthe counter lay some sliced cucumber, some pieces of dried black\nbread, and some fish, chopped up small, all smelling very bad.\nIt was insufferably close, and so heavy with the fumes of spirits\nthat five minutes in such an atmosphere might well make a man\ndrunk.\nThere are chance meetings with strangers that interest us\nfrom the first moment, before a word is spoken. Such was the",
        "expected_out": "**His wife a year he fondly loved\nHis wife a — a year he — fondly loved.**\nOr suddenly waking up again:\n\"Walking along the crowded row\nHe met the one he used to know.\"\nBut no one shared his enjoyment: his silent companion looked\nwith positive hostility and mistrust at all these manifestations.\nThere was another man in the room who looked somewhat like\na retired government clerk. He was sitting apart, now and then\nsipping from his pot and looking round at the company. He,\ntoo, appeared to be in some agitation.\nCHAPTER II\nRaskolnikov was not used to crowds, and, as we said before,\nhe avoided society of every sort, more especially of late. But now\nall at once he felt a desire to be with other people. Something\nnew seemed to be taking place within him, and with it he felt\na sort of thirst for company. He was so weary after a whole\nmonth of concentrated wretchedness and gloomy excitement\nthat he longed to rest, if only for a moment, in some other world,\nwhatever it might be; and, in spite of the filthiness of the sur-\nroundings, he was glad now to stay in the tavern.\nThe master of the establishment was in another room, but he\nfrequently came down some steps into the main room, his\njaunty, tarred boots with red turn-over tops coming into view\neach time before the rest of his person. He wore a full coat and\na horribly greasy black satin waistcoat, with no cravat, and his\nwhole face seemed smeared with oil like an iron lock. At the\ncounter stood a boy of about fourteen, and there was another\nboy somewhat younger who handed whatever was wanted. On\nthe counter lay some sliced cucumber, some pieces of dried black\nbread, and some fish, chopped up small, all smelling very bad.\nIt was insufferably close, and so heavy with the fumes of spirits\nthat five minutes in such an atmosphere might well make a man\ndrunk.\nThere are chance meetings with strangers that interest us\nfrom the first moment, before a word is spoken. Such was the",
    },
    {
        "inp": "26 CRIME AND PUNISHMENT\nwept over it and grown used to it. Man grows used to every-\nthing, the s coundrel!\"\nHe sank into thought.\n\"And what if I am wrong,\" he cried suddenly after a mo-\nment's thought. \"What if man is not really a scoundrel, man in\ngeneral, I mean, the whole race of mankind — then all the rest\nis prejudice, simply artificial terrors and there are no barriers\nand it's all as it should be.\"\nCHAPTER in\nHe waked up late next day after a broken sleep. But his sleep\nhad not refreshed him; he waked up bilious, irritable, ill-tem-\npered, and looked with hatred at his room. It was a tiny cup-\nboard of a room about six paces in length. It had a poverty-\nstricken appearance with its dusty yellow paper peeling oflf the\nwalls, and it was so low-pitched that a man of more than aver-\nage height was ill at ease in it and felt every moment that he\nwould knock his head against the ceiling. The furniture was in\nkeeping with the room: there were three old chairs, rather\nrickety; a painted table in the corner on which lay a few manu-\nscripts and books; the dust that lay thick upon them showed\nthat they had been long untouched. A big clumsy sofa occupied\nalmost the whole of one wall and half the floor space of the\nroom; it was once covered with chintz, but was now in rags\nand served Raskolnikov as a bed. Often he went to sleep on it,\nas he was, without undressing, without sheets, wrapped in his\nold student's overcoat, with his head on one little pillow, under\nwhich he heaped up all the linen he had, clean and dirty, by\nway of a bolster. A little table stood in front of the sofa.\nIt would have been difficult to sink to a lower ebb of dis-\norder, but to Raskolnikov in his present state of mind this was\npositively agreeable. He had got completely away from every\none, like a tortoise in its shell, and even the sight of the servant\ngirl who had to wait upon him and looked sometimes into his\nroom made him writhe with nervous irritation. He was in the\ncondition that overtakes some monomaniacs entirely concen-\ntrated upon one thing. His landlady had for the last fortnight\ngiven up sending him in meals, and he had not yet thought of",
        "expected_out": "wept over it and grown used to it. Man grows used to every-\nthing, the scoundrel!\"\nHe sank into thought.\n\"And what if I am wrong,\" he cried suddenly after a mo-\nment's thought. \"What if man is not really a scoundrel, man in\ngeneral, I mean, the whole race of mankind — then all the rest\nis prejudice, simply artificial terrors and there are no barriers\nand it's all as it should be.\"\nCHAPTER III\nHe waked up late next day after a broken sleep. But his sleep\nhad not refreshed him; he waked up bilious, irritable, ill-tem-\npered, and looked with hatred at his room. It was a tiny cup-\nboard of a room about six paces in length. It had a poverty-\nstricken appearance with its dusty yellow paper peeling off the\nwalls, and it was so low-pitched that a man of more than aver-\nage height was ill at ease in it and felt every moment that he\nwould knock his head against the ceiling. The furniture was in\nkeeping with the room: there were three old chairs, rather\nrickety; a painted table in the corner on which lay a few manu-\nscripts and books; the dust that lay thick upon them showed\nthat they had been long untouched. A big clumsy sofa occupied\nalmost the whole of one wall and half the floor space of the\nroom; it was once covered with chintz, but was now in rags\nand served Raskolnikov as a bed. Often he went to sleep on it,\nas he was, without undressing, without sheets, wrapped in his\nold student's overcoat, with his head on one little pillow, under\nwhich he heaped up all the linen he had, clean and dirty, by\nway of a bolster. A little table stood in front of the sofa.\nIt would have been difficult to sink to a lower ebb of dis-\norder, but to Raskolnikov in his present state of mind this was\npositively agreeable. He had got completely away from every\none, like a tortoise in its shell, and even the sight of the servant\ngirl who had to wait upon him and looked sometimes into his\nroom made him writhe with nervous irritation. He was in the\ncondition that overtakes some monomaniacs entirely concen-\ntrated upon one thing. His landlady had for the last fortnight\ngiven up sending him in meals, and he had not yet thought of",
    },
    {
        "inp": "CRIME AND PUNISHMENT 35\nman ought not to be indebted to his wife, but that it is bettef\nfor a wife to look upon her husband as her benefactor. I must\nadd that he expressed it more nicely and politely than I have\ndone, for I h ave forgotten his actual phrases and only remember\nthe meaning. And, besides, it was obviously not said of design,\nbut slipped out in the heat of conversation, so that he tried\nafterwards to correct himself and smooth it over, but all the\nsame it did strike me as somewhat rude, and I said so afterwards\nto Dounia. But Dounia was vexed, and answered that 'words\nare not deeds,' and that, of course, is perfectly true. Dounia did\nnot sleep all night before she made up her mind, and, thinking\nthat I was asleep, she got out of bed and was walking up and\ndown the room all night; at last she knelt down before the ikon\nand pj-ayed long and fervently and in the morning she told me\nthat she had decided.\n\"I have mentioned already that Pyotr Petrovitch is just setting\nofif for Petersburg, where he has a great deal of business, and he\nwants to open a legal bureau. He has been occupied for many\nyears in conducting civil and commercial litigation, and only\nthe other day he won an important case. He has to be in Peters-\nburg because he has an important case before the Senate. So,\nRodya dear, he may be of the greatest use to you, in every way\nindeed, and Dounia and I have agreed that from this very day\nyou could definitely enter upon your career and might consider\nthat your future is marked out and assured for you. Oh, if only\nthis comes to pass! This would be such a benefit that we could\nonly look upon it as a providential blessing. Dounia is dreaming\nof nothing else. We have even .ventured already to drop a few\nwords on the subject to Pyotr Petrovitch. He was cautious in\nhis answer, and said that, of course, as he could not get on\nwithout a secretary, it would be better to be paying a salary to a\nrelation than to a stranger, if only the former were fitted for the\nduties (as though there could be doubt of your being fitted!)\nbut then he expressed doubts whether your studies at the uni-\nversity would leave you time for work at his office. The matter\ndropped for the time, but Dounia is thinking of nothing else\nnow. She has been in a sort of fever for the last few days, and\nhas already made a regular plan for your becoming in the end an\nassociate and even a partner in Pyotr Petrovitch's legal business,\nwhich might well be, seeing that you are a stulent of law. I am",
        "expected_out": "man ought not to be indebted to his wife, but that it is better\nfor a wife to look upon her husband as her benefactor. I must\nadd that he expressed it more nicely and politely than I have\ndone, for I have forgotten his actual phrases and only remember\nthe meaning. And, besides, it was obviously not said of design,\nbut slipped out in the heat of conversation, so that he tried\nafterwards to correct himself and smooth it over, but all the\nsame it did strike me as somewhat rude, and I said so afterwards\nto Dounia. But Dounia was vexed, and answered that 'words\nare not deeds,' and that, of course, is perfectly true. Dounia did\nnot sleep all night before she made up her mind, and, thinking\nthat I was asleep, she got out of bed and was walking up and\ndown the room all night; at last she knelt down before the ikon\nand prayed long and fervently and in the morning she told me\nthat she had decided.\n\"I have mentioned already that Pyotr Petrovitch is just setting\noff for Petersburg, where he has a great deal of business, and he\nwants to open a legal bureau. He has been occupied for many\nyears in conducting civil and commercial litigation, and only\nthe other day he won an important case. He has to be in Peters-\nburg because he has an important case before the Senate. So,\nRodya dear, he may be of the greatest use to you, in every way\nindeed, and Dounia and I have agreed that from this very day\nyou could definitely enter upon your career and might consider\nthat your future is marked out and assured for you. Oh, if only\nthis comes to pass! This would be such a benefit that we could\nonly look upon it as a providential blessing. Dounia is dreaming\nof nothing else. We have even ventured already to drop a few\nwords on the subject to Pyotr Petrovitch. He was cautious in\nhis answer, and said that, of course, as he could not get on\nwithout a secretary, it would be better to be paying a salary to a\nrelation than to a stranger, if only the former were fitted for the\nduties (as though there could be doubt of your being fitted!)\nbut then he expressed doubts whether your studies at the uni-\nversity would leave you time for work at his office. The matter\ndropped for the time, but Dounia is thinking of nothing else\nnow. She has been in a sort of fever for the last few days, and\nhas already made a regular plan for your becoming in the end an\nassociate and even a partner in Pyotr Petrovitch's legal business,\nwhich might well be, seeing that you are a student of law. I am",
    },
    {
        "inp": "81 Hamlet ACT 2. SC. 2\nFTLN 1046 And leads the will to desperate undertakings\nFTLN 1047 As oft as any passions under heaven\nFTLN 1048 That does afflict our natures. I am sorry.\nFTLN 1049 What, have you given him any hard words of late?\nOPHELIA\nFTLN 1050 No, my good lord, but as you did command 120\nFTLN 1051 I did repel his letters and denied\nFTLN 1052 His access to me.\nFTLN 1053 POLONIUS That hath made him mad.\nFTLN 1054 I am sorry that with better heed and judgment\nFTLN 1055 I had not coted him. I feared he did but trifle 125\nFTLN 1056 And meant to wrack thee. But beshrew my jealousy!\nFTLN 1057 By heaven, it is as proper to our age\nFTLN 1058 To cast beyond ourselves in our opinions\nFTLN 1059 As it is common for the younger sort\nFTLN 1060 To lack discretion. Come, go we to the King. 130\nFTLN 1061 This must be known, which, being kept close, might\nFTLN 1062 move\nFTLN 1063 More grief to hide than hate to utter love.\nFTLN 1064 Come.\nThey exit.\nScene 2\nFlourish. Enter King and Queen, Rosencrantz and\nGuildenstern and Attendants.\nKING\nFTLN 1065 Welcome, dear Rosencrantz and Guildenstern.\nFTLN 1066 Moreover that we much did long to see you,\nFTLN 1067 The need we have to use you did provoke\nFTLN 1068 Our hasty sending. Something have you heard\nFTLN 1069 Of Hamlet’s transformation, so call it, 5\nFTLN 1070 Sith nor th’ exterior nor the inward man\nFTLN 1071 Resembles that it was. What it should be,\nFTLN 1072 More than his father’s death, that thus hath put him",
        "expected_out": "And leads the will to desperate undertakings\nAs oft as any passions under heaven\nThat does afflict our natures. I am sorry.\nWhat, have you given him any hard words of late?\nOPHELIA\nNo, my good lord, but as you did command\nI did repel his letters and denied\nHis access to me.\nPOLONIUS\nThat hath made him mad.\nI am sorry that with better heed and judgment\nI had not coted him. I feared he did but trifle\nAnd meant to wrack thee. But beshrew my jealousy!\nBy heaven, it is as proper to our age\nTo cast beyond ourselves in our opinions\nAs it is common for the younger sort\nTo lack discretion. Come, go we to the King.\nThis must be known, which, being kept close, might\nmove\nMore grief to hide than hate to utter love.\nCome.\nThey exit.\nScene 2\nFlourish. Enter King and Queen, Rosencrantz and\nGuildenstern and Attendants.\nKING\nWelcome, dear Rosencrantz and Guildenstern.\nMoreover that we much did long to see you,\nThe need we have to use you did provoke\nOur hasty sending. Something have you heard\nOf Hamlet’s transformation, so call it,\nSith nor th’ exterior nor the inward man\nResembles that it was. What it should be,\nMore than his father’s death, that thus hath put him",
    },
]


def main():
    """
    Runs the text cleaning evaluation script.

    This function initializes the TextCleanupClient, iterates through a list of
    test cases (EXAMPLES), and for each case, it calls the cleaning service.
    It then compares the actual output with the expected output and prints
    any discrepancies to the console. This allows for qualitative assessment
    of the text cleaning model's performance on a variety of inputs.
    """
    for i, example in enumerate(EXAMPLES):
        inp = example["inp"]
        expected_out = example["expected_out"]

        actual_out = clean_text(inp)

        if not actual_out:
            print(f"--- NO OUTPUT FOR EXAMPLE {i+1} ---")
            print("--- INPUT ---")
            print(inp)
            print("\n" * 3)
            continue

        if actual_out.strip() != expected_out.strip():
            print(f"--- MISMATCH ON EXAMPLE {i+1} ---")
            print("--- INPUT ---")
            print(inp)
            print("\n--- EXPECTED ---")
            print(expected_out)
            print("\n--- ACTUAL ---")
            print(actual_out)
            print("\n" * 3)


if __name__ == "__main__":
    main()